name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: ["1.24", "1.25"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go test -v -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
